version: "3.8"
services:
  online-shop:
    image: front-end-online-book-shop-image
    container_name: front-end-online-book-shop-container
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8083:5173"
