version: "3.8"
services:
  online-shop:
    image: test-jenkins
    container_name: test-jenkins-container
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8083:5173"
